import pandas as pd
import re, os

os.system("clear")

texto_certidao = """
GOVERNO DO ESTADO DE SÃO PAULO
SECRETARIA DE DESENVOLVIMENTO ECONÔMICO
JUNTA COMERCIAL DO ESTADO DE SÃO PAULO
CERTIDÃO SIMPLIFICADA
CERTIFICAMOS QUE AS INFORMAÇÕES ABAIXO CONSTAM DOS DOCUMENTOS ARQUIVADOS NESTA JUNTA COMERCIAL E SÃO VIGENTES
NA DATA DE SUA EXPEDIÇÃO.
SE HOUVER ARQUIVAMENTOS POSTERIORES, ESTA CERTIDÃO PERDERÁ SUA VALIDADE.
A AUTENTICIDADE DESTA CERTIDÃO E A EXISTÊNCIA DE ARQUIVAMENTOS POSTERIORES, SE HOUVER, PODERÃO SER CONSULTADAS NO
SITE WWW.JUCESPONLINE.SP.GOV.BR, MEDIANTE O CÓDIGO DE AUTENTICIDADE INFORMADO AO FINAL DO DOCUMENTO.
EMPRESA
NIRE REGISTRO DATA DA CONSTITUIÇÃO INÍCIO DAS ATIVIDADES PRAZO DE DURAÇÃO
35211820431 10/09/1993 24/08/1993
NOME COMERCIAL TIPO JURÍDICO
NESS PROCESSOS E TECNOLOGIA LTDA. SOCIEDADE LIMITADA
C.N.P.J. ENDEREÇO NÚMERO COMPLEMENTO
72.027.097/0001-37 RUA DOUTOR GERALDO CAMPOS MOREIRA 240 ANDAR 14
BAIRRO MUNICÍPIO UF CEP MOEDA VALOR CAPITAL
CIDADE MONCOES SAO PAULO SP 04571-020 R$ 681.400,00
OBJETO SOCIAL
SUPORTE TÉCNICO, MANUTENÇÃO E OUTROS SERVIÇOS EM TECNOLOGIA DA INFORMAÇÃO
COMÉRCIO ATACADISTA DE EQUIPAMENTOS DE INFORMÁTICA
COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENTOS DE TELEFONIA E COMUNICAÇÃO
ALUGUEL DE MÁQUINAS E EQUIPAMENTOS PARA ESCRITÓRIO
CONSULTORIA EM TECNOLOGIA DA INFORMAÇÃO
EXISTEM OUTRAS ATIVIDADES
SÓCIO
NOME
CAMILA FENERICH LUCRI
ENDEREÇO NÚMERO COMPLEMENTO
RUA PADRE CALDAS BARBOSA 155 APTO 1702
BAIRRO MUNICÍPIO UF CEP RG
VILA GUILHERME SAO PAULO SP 02055-050 278304187
CPF CARGO QUANTIDADE COTAS
292.933.038-41 SÓCIO 27.254,00
SÓCIO
NOME
DANIEL AJZEN
ENDEREÇO NÚMERO COMPLEMENTO
AVENIDA ALBERT BARTHOLOME 172 BL A FL AP78
BAIRRO MUNICÍPIO UF CEP RG
JARDIM DAS VERTENTE SAO PAULO SP 05541-000 34893002
CPF CARGO QUANTIDADE COTAS
312.042.418-80 SÓCIO 1,00
SÓCIO
NOME
Documento Gratuito Página 1 de 4
Proibida a ComercializaçãoGOVERNO DO ESTADO DE SÃO PAULO
SECRETARIA DE DESENVOLVIMENTO ECONÔMICO
JUNTA COMERCIAL DO ESTADO DE SÃO PAULO
CERTIDÃO SIMPLIFICADA
FERNANDO DIAS RIBEIRO
ENDEREÇO NÚMERO COMPLEMENTO
AVENIDA MOFARREJ 346
BAIRRO MUNICÍPIO UF CEP RG
VILA LEOPOLDINA SAO PAULO SP 05311-000 261182031
CPF CARGO QUANTIDADE COTAS
212.551.148-78 SÓCIO 27.254,00
SÓCIO
NOME
JLCOELHO TECNOLOGIA, OPERACOES E PARTICIPACOES LTDA
ENDEREÇO NÚMERO COMPLEMENTO
RUA OLIMPIADAS 205
BAIRRO MUNICÍPIO UF CEP
VILA OLIMPIA SAO PAULO SP 04551-000
NIRE CARGO QUANTIDADE COTAS
35228421402 SÓCIO 68.143,00
SÓCIO
NOME
MARCOS VENICIUS DOS SANTOS SILVA
ENDEREÇO NÚMERO COMPLEMENTO
AVENIDA ROUXINOL 174 APTO. 81
BAIRRO MUNICÍPIO UF CEP RG
INDIANOPOLIS SAO PAULO SP 04516-000 5692015
CPF CARGO QUANTIDADE COTAS
904.230.032-91 SÓCIO 1,00
SÓCIO
NOME
MONICA BARBOSA YOSHIDA
ENDEREÇO NÚMERO COMPLEMENTO
AVENIDA RAMALHO ORTIGAO 374 APT. 151
BAIRRO MUNICÍPIO UF CEP RG
VILA GUMERCINDO SAO PAULO SP 04130-010 10869837
CPF CARGO QUANTIDADE COTAS
065.924.278-84 SÓCIO 1,00
SÓCIO E ADMINISTRADOR
NOME
RICARDO ESPER
ENDEREÇO NÚMERO COMPLEMENTO
RUA BARAO DE CAMPOS GERAIS 133
BAIRRO MUNICÍPIO UF CEP RG
REAL PARQUE SAO PAULO SP 05684-000 155575375
CPF CARGO QUANTIDADE COTAS
073.612.518-38 SÓCIO E ADMINISTRADOR 422.470,00
Documento Gratuito Página 2 de 4
Proibida a ComercializaçãoGOVERNO DO ESTADO DE SÃO PAULO
SECRETARIA DE DESENVOLVIMENTO ECONÔMICO
JUNTA COMERCIAL DO ESTADO DE SÃO PAULO
CERTIDÃO SIMPLIFICADA
SÓCIO E ADMINISTRADOR
NOME
ROGERIO SALERNO
ENDEREÇO NÚMERO COMPLEMENTO
AL DOS GUATAS 1341
BAIRRO MUNICÍPIO UF CEP
PLANALTO PAULISTA SAO PAULO SP 04053-043
CPF CARGO QUANTIDADE COTAS
099.869.908-07 SÓCIO E ADMINISTRADOR 136.275,00
SÓCIO
NOME
THIAGO BERTUZZI PACIENCIA
ENDEREÇO NÚMERO COMPLEMENTO
RUA RIO VERDE 879 APTO 34
BAIRRO MUNICÍPIO UF CEP RG
VILA BRUNA SAO PAULO SP 02934-001 415779170
CPF CARGO QUANTIDADE COTAS
229.877.158-89 SÓCIO 1,00
"""

# Remover as seções indesejadas do texto
texto_certidao = re.sub(r'Documento Gratuito Página \d de \d.*?CERTIDÃO SIMPLIFICADA', '', texto_certidao, flags=re.DOTALL)

# Padrão para encontrar o valor do capital
padrao_valor_capital = re.compile(r'VALOR CAPITAL[^R\$]R\$\s([\d.]+,\d{2})', re.IGNORECASE)

# Realizar a busca no texto
match = padrao_valor_capital.search(texto_certidao)

# Extrair o valor se encontrado
valor_capital = match.group(1)
if match:
    # Substituir ponto por nada e vírgula por ponto
    valor_str_formatado = valor_capital.replace('.', '').replace(',', '.')
    # Converter para float
    valor_float = float(valor_str_formatado)
else: 
    "Valor não encontrado"

padrao_socio = re.compile(r'((?:SÓCIO|SÓCIO E ADMINISTRADOR)[\s\S]+?)(?:(\d{1,3}(?:\.\d{3})*,\d{2})\n)', re.DOTALL)
socios_brutos = padrao_socio.findall(texto_certidao)


dados_socios = []
i=0

for bloco_socio in socios_brutos:
    # Encontrar o nome do sócio
    #match_nome = re.search(r'NOME\n(.*?)\n', socios_brutos[i][0])
    match_nome = re.search(r'NOME\n+\s*(.*?)\n', socios_brutos[i][0])
    nome_socio = match_nome.group(1).strip() if match_nome else "Nome não encontrado"

    # Encontrar a quantidade de cotas
    #match_cotas = re.search(r'QUANTIDADE COTAS\s*\n\s*(\d{1,3}(?:\.\d{3})*,\d{2})', bloco_socio)
    match_cotas = re.search(r'(\d{1,3}(?:\.\d{3})*,\d{2})', socios_brutos[i][1])

    cotas = match_cotas.group(1) if match_cotas else "0,00"

    if match:
        # Substituir ponto por nada e vírgula por ponto
        cotas_str_formatado = cotas.replace('.', '').replace(',', '.')
        # Converter para float
        cotas_float = float(cotas_str_formatado)
    else: 
        "0.00"

    percentual_cotas = round((cotas_float/valor_float)*100,2)
    dados_socios.append((nome_socio, cotas, percentual_cotas, valor_capital))

    i= i + 1

# Criar um DataFrame a partir dos dados extraídos
df_socios = pd.DataFrame(dados_socios, columns=['nome_socio', 'quantidade_de_cotas', 'percentual_de_cotas', 'capital_social_empresa' ])

# Imprimir o DataFrame
print(df_socios)
